language: c

# try to compile on older & newset available versions of linux & osx:
#   - https://docs.travis-ci.com/user/reference/linux/
#   - https://docs.travis-ci.com/user/reference/osx/
jobs:
  include:
    # - os: linux
    #   dist: focal
    #   compiler: gcc
    # - os: linux
    #   dist: focal
    #   compiler: clang
    # - os: linux
    #   dist: trusty
    #   compiler: gcc
    # - os: linux
    #   dist: trusty
    #   compiler: clang
    - os: osx
      osx_image: xcode12u
      compiler: clang
      env: ARCH=x64
    - os: osx
      osx_image: xcode7.3
      compiler: clang
      env: ARCH=x64

before_install:
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update -qq; fi
      # support CC=gcc ARCH=x86:
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y gcc-multilib; fi
      # support CC=clang ARCH=x86:
    # - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y gcc-4.9-multilib; fi

script:
    - ./test/run.sh
  
# only trigger build for pushes on master branch
branches:
  only:
    - master
